dist: bionic
language: go
go:
  - 1.16.x
git:
  depth: 1
install: true
before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
    | sh -s -- -b $(go env GOPATH)/bin v1.39.0
script:
  - make all